<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows7.0</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>
		<AssemblyName>ListaAvisosApp</AssemblyName>
		<RootNamespace>ListaAvisosApp</RootNamespace>
		<ApplicationIcon>icon.ico</ApplicationIcon>
	</PropertyGroup>

  <ItemGroup>
    <None Remove="icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="icon.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <!-- Se o NuGet reclamar de versão, use "Gerenciar Pacotes NuGet" no
         Visual Studio e atualize para a versão mais recente estável. -->
    <PackageReference Include="CsvHelper" Version="33.0.1" />
    <PackageReference Include="QuestPDF" Version="2024.10.3" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
